version: "3.8"

services:
  weather-backend-app:
    build: 
      context: .
      dockerfile: src/TheWeather.Api/Dockerfile
    ports:
      - "80:80"
    container_name: weather-backend-app

  weather-frontend-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    container_name: weather-frontend-app
    depends_on:
      - weather-backend-app